from datetime import datetime
from typing import Protocol
from uuid import UUID

from valor.runtime_identity.domain.models import RuntimeCredential, RuntimePrincipal


class RuntimePrincipalRepository(Protocol):
    async def add(self, principal: RuntimePrincipal) -> None: ...
    async def get(self, principal_id: UUID) -> RuntimePrincipal | None: ...
    async def disable(self, principal: RuntimePrincipal) -> None: ...
    async def initialize_usage_limits(self, principal: RuntimePrincipal) -> bool: ...


class RuntimeCredentialRepository(Protocol):
    async def add(self, credential: RuntimeCredential) -> None: ...
    async def get(self, credential_id: UUID) -> RuntimeCredential | None: ...
    async def revoke(self, credential: RuntimeCredential) -> None: ...
    async def has_potentially_usable(self, principal_id: UUID, now: datetime) -> bool: ...
