from datetime import datetime
from typing import Protocol
from uuid import UUID

from valor.runtime_identity.domain.models import RuntimeCredential, RuntimePrincipal


class RuntimePrincipalRepository(Protocol):
    async def add(self, principal: RuntimePrincipal) -> None: ...
    async def get(self, principal_id: UUID) -> RuntimePrincipal | None: ...
    async def get_for_update(self, principal_id: UUID) -> RuntimePrincipal | None: ...
    async def disable(self, principal: RuntimePrincipal) -> None: ...
    async def initialize_usage_limits(self, principal: RuntimePrincipal) -> bool: ...
    async def lock_legacy_identity(self, legacy_id: str) -> None: ...
    async def legacy_identity_is_claimed(self, legacy_id: str) -> bool: ...
    async def bind_identity_continuity(self, principal: RuntimePrincipal) -> bool: ...


class RuntimeCredentialRepository(Protocol):
    async def add(self, credential: RuntimeCredential) -> None: ...
    async def get(self, credential_id: UUID) -> RuntimeCredential | None: ...
    async def revoke(self, credential: RuntimeCredential) -> None: ...
    async def has_potentially_usable(self, principal_id: UUID, now: datetime) -> bool: ...
