from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from valor.management_identity.domain.models import ManagementCredential, ManagementPrincipal


class ManagementPrincipalRepository(Protocol):
    async def add(self, principal: ManagementPrincipal) -> None: ...
    async def get(self, principal_id: UUID) -> ManagementPrincipal | None: ...
    async def replace_scopes(self, principal: ManagementPrincipal) -> None: ...
    async def disable(self, principal: ManagementPrincipal) -> None: ...
    async def count(self) -> int: ...
    async def has_recoverable_manager(
        self, *, excluding_principal_id: UUID | None = None
    ) -> bool: ...


class ManagementCredentialRepository(Protocol):
    async def add(self, credential: ManagementCredential) -> None: ...
    async def get(self, credential_id: UUID) -> ManagementCredential | None: ...
    async def list_for_principal(self, principal_id: UUID) -> Sequence[ManagementCredential]: ...
    async def revoke(self, credential: ManagementCredential) -> None: ...
    async def has_usable_for_principal(self, principal_id: UUID) -> bool: ...
